CREATE OR REPLACE TABLE "DEALS" AS
SELECT D."ID", D."DEALNAME",
D."HS_FORECAST_AMOUNT",D."CREATEDATE",D."HS_IS_CLOSED",D."HS_DEAL_STAGE_PROBABILITY", D."DAYS_TO_CLOSE",
D."HS_CREATED_BY_USER_ID", D."HS_PROJECTED_AMOUNT", D."HS_IS_CLOSED_WON",D."HS_CLOSED_AMOUNT_IN_HOME_CURRENCY",
D."DESCRIPTION", D."AMOUNT_IN_HOME_CURRENCY",D."HS_CLOSED_AMOUNT",D."CLOSEDATE",D."DEALTYPE",D."AMOUNT",D."HS_LASTMODIFIEDDATE",
D."PIPELINE" , PS."LABEL" AS "DEALSTAGE", PS."DISPLAY_ORDER" AS "PIPELINE_DISPLAY_ORDER", 
CASE WHEN D."HS_IS_CLOSED_WON" = 'true' THEN D."CLOSEDATE" ELSE NULL END AS "HS_DATE_ENTERED_CLOSEDWON",
TO_DATE(D."CREATEDATE") AS "CREATED_AT_DATE",
TO_TIME(D."CREATEDATE") AS "CREATED_AT_TIME"
FROM "HS_DEALS" D
LEFT JOIN "HS_DEALS_PIPELINE_STAGES" PS 
ON D."PIPELINE" = PS."PIPELINE_ID" AND D."DEALSTAGE"=PS."ID";
