CREATE TABLE "OWNER"
(
   "ID" VARCHAR(2000),
   "EMAIL" VARCHAR(255),
   "FIRST_NAME" VARCHAR(255),
   "LAST_NAME" VARCHAR(255),
   "USER_ID" VARCHAR(255),
   "ARCHIVED" BOOLEAN
);

INSERT INTO "OWNER"
SELECT "ID", "EMAIL", "FIRST_NAME", "LAST_NAME","USER_ID", "ARCHIVED"
   FROM "HS_OWNERS";
