CREATE OR REPLACE TABLE "sklik"(
  "src_id" varchar (100),
  "user_id" varchar (100) ,
  "account_id" varchar (100), 
  "platform_id" varchar(100),
  "account_name" varchar (100),
  "ads_id" integer ,
  "ads_name" varchar (100) ,
  "created_date" date,
  "start_date" date,
  "modified_date" date,
  "end_date" date, 
  "campaign_id" integer,
  "campaign_name" varchar (100), 
  "currency_id" varchar (10), 
  "spent_amount" NUMBER(24,3), 
  "reach" NUMBER(24,0),
  "impressions" NUMBER(24,0), 
  "frequency" NUMBER(24,3),
  "cpm" NUMBER(24,3), 
  "cpv" NUMBER(24,3),
  "link_clicks" NUMBER(24,0),
  "ctr" NUMBER(24,3),
  "post_comments" NUMBER(24,0),
  "post_reactions" NUMBER(24,0),
  "post_shares" NUMBER(24,0),
  "video_views" NUMBER(24,0),
  "view_rate"  NUMBER(24,0),
  "six_sec_video_view" NUMBER(24,0), 
  "full_video_view" NUMBER(24,0),
  "est_ad_recall_lift" NUMBER(24,0),
  "est_ad_recall_lift_rate" NUMBER(24,3),
  "active_view_measurability" NUMBER(24,3),
  "landing_page_clicks" NUMBER(24,0),
  "paid_comments" NUMBER(24,0),
  "paid_likes" NUMBER(24,0), 
  "paid_shares" NUMBER(24,0)
 );

INSERT INTO "sklik" 
(
   "src_id",
   "user_id",
  "account_id",
  "platform_id", 
  "account_name",
  "ads_id",
  "ads_name",
  "created_date",
  "start_date" , 
  "modified_date" , 
  "end_date" , 
  "campaign_id" , 
  "campaign_name" , 
  "currency_id" , 
  "spent_amount" ,
  "reach",
  "impressions", 
  "frequency",
  "cpm", 
  "link_clicks",
  "ctr",
  "cpv",
  "post_comments",
  "post_reactions",
  "post_shares",
  "video_views",
  "view_rate",
  "six_sec_video_view",
  "full_video_view",
  "est_ad_recall_lift",
  "est_ad_recall_lift_rate",
  "active_view_measurability",
  "landing_page_clicks",
  "paid_comments",
  "paid_likes", 
  "paid_shares" 
)
SELECT 
    ----!!! start  date neni vsude vyplnen
    --concat ('SKLIK.', AST."id", '.', TO_DATE(NULLIF(SUBSTRING(C."startDate", 1, 8), ''), 'YYYYMMDD')),
    concat ('SKLIK.', AST."id", '.', TO_DATE(NULLIF(SUBSTRING(AD."createDate", 1, 8), ''), 'YYYYMMDD')),
    NULL,--user_id,
    AD."accountId",
    'SKLIK',
    ACC."username",
    AD."id", 
    AD."name",
    TO_DATE(NULLIF(SUBSTRING(AD."createDate", 1, 8), ''), 'YYYYMMDD') AS "createDate",
    TO_DATE(NULLIF(SUBSTRING(C."startDate", 1, 8), ''), 'YYYYMMDD') AS "startDate",
    NULL, --modified_date , 
    TO_DATE(NULLIF(SUBSTRING(C."endDate", 1, 8), ''), 'YYYYMMDD') AS "endDate",
    AD."campaign_id", 
    AD."campaign_name", 
    NULL,-- currency_id , 
    AST."totalMoney", --?
    NULL,--reach,
    AST."impressions", 
    NULL,--frequency,
    CASE WHEN AST."impressions" <> 0 THEN AST."totalMoney" / AST."impressions" * 1000 ELSE 0 END,   --cpm, total money?, 
    AST."clicks",
    AST."ctr",
    NULL,
    NULL,--post_comments,
    NULL,--post_reactions,
    NULL,--post_shares,
    AST."views",
    NULL,
  NULL,-- six_sec_video_view,
  NULL, --full_video_view,
  NULL,--est_ad_recall_lift,
  NULL,--est_ad_recall_lift_rate,
  NULL, --active_view_measurability, ?
  NULL, --landing_page_clicks,
  NULL, --paid_comments,
  NULL,--paid_likes, 
  NULL--paid_shares 
FROM "sklik_ads-stats" AST
LEFT JOIN "sklik_ads" AD
    ON  AST."id" = AD."id"
LEFT JOIN "sklik_accounts" ACC
    ON AD."accountId" = ACC."userId"
LEFT JOIN "sklik_campaign" C
    ON AD."campaign_id" = C."id"
;
