-- HS_HUBSPOT."PUBLIC".HS_DEALS_PIPELINES 
CREATE TABLE HS_DEALS_PIPELINES 
AS
SELECT DISTINCT
	"pipelineId" AS ID,
	"label" AS LABEL,
	CASE WHEN "active" = 'True' THEN 'False' ELSE 'True' END AS ARCHIVED
FROM "pipelines"
;
