CREATE TABLE "COMPANIES"
(
    "ID" VARCHAR(2000), 
    "INDUSTRY" VARCHAR(255), 
    "CITY" VARCHAR(255),
    "NUMBEROFEMPLOYEES" INTEGER, 
    "HS_NUM_OPEN_DEALS" INTEGER, 
    "STATE" VARCHAR(255), 
    "NAME" VARCHAR(255), 
    "TOTAL_REVENUE" NUMERIC, 
    "CREATED_AT" VARCHAR(255), 
    "ARCHIVED" BOOLEAN, 
    "COUNTRY" VARCHAR(255), 
    "CREATEDATE" VARCHAR(255), 
    "HS_ANALYTICS_SOURCE" VARCHAR(255), 
    "ZIP" VARCHAR(255), 
    "WEBSITE" VARCHAR(255),
    "CREATED_AT_DATE" DATE,
    "CREATED_AT_TIME" TIME
    "HS_IS_TARGET_ACCOUNT" VARCHAR(255),
    "UPDATED_AT" VARCHAR(255),
    "HS_ANALYTICS_LAST_VISIT_DATE" DATE,
    "HS_ANALYTICS_NUM_VISITS" NUMERIC
);

INSERT INTO "COMPANIES"
SELECT "ID", "INDUSTRY", "CITY","NUMBEROFEMPLOYEES", "HS_NUM_OPEN_DEALS", "STATE", "NAME", "TOTAL_REVENUE", 
"CREATED_AT", "ARCHIVED", "COUNTRY", "CREATEDATE", "HS_ANALYTICS_SOURCE", "ZIP", "WEBSITE",TO_DATE("CREATEDATE") AS  "CREATED_AT_DATE",
TO_TIME("CREATEDATE") AS  "CREATED_AT_TIME","HS_IS_TARGET_ACCOUNT",TO_DATE(NULLIF("UPDATED_AT",'')) AS  "UPDATED_AT",
TO_DATE(NULLIF("HS_ANALYTICS_LAST_VISIT_TIMESTAMP",'')) AS  "HS_ANALYTICS_LAST_VISIT_DATE","HS_ANALYTICS_NUM_VISITS",
ifnull("LIFECYCLESTAGE",'Subscriber') AS "LIFECYCLESTAGE"
FROM "HS_COMPANIES";
