CREATE OR REPLACE TABLE "ads_insight_fact" (
  "src_id" varchar (100),
  "user_id" varchar (100) ,
  "account_id" varchar (100), 
  "platform_id" varchar(100),
  "account_name" varchar (100),
  "ads_id" integer ,
  "ads_name" varchar (100) ,
  "created_date" date,
  "start_date" date,
  "start_date_ym"  varchar (100),
  "start_date_w"  varchar (100),
  "modified_date" date,
  "end_date" date, 
  "campaign_id" integer,
  "campaign_name" varchar (100), 
  "currency_id" varchar (10), 
  "spent_amount" NUMBER(24,3), 
  "reach" NUMBER(24,0),
  "impressions" NUMBER(24,0), 
  "frequency" NUMBER(24,3),
  "cpm" NUMBER(24,3), 
  "cpv" NUMBER(24,3),
  "link_clicks" NUMBER(24,0),
  "ctr" NUMBER(24,3),
  "post_comments" NUMBER(24,0),
  "post_reactions" NUMBER(24,0),
  "post_shares" NUMBER(24,0),
  "video_views" NUMBER(24,0),
  "view_rate"  NUMBER(24,0),
  "six_sec_video_view" NUMBER(24,0), 
  "full_video_view" NUMBER(24,0),
  "est_ad_recall_lift" NUMBER(24,0),
  "est_ad_recall_lift_rate" NUMBER(24,3),
  "active_view_measurability" NUMBER(24,3),
  "landing_page_clicks" NUMBER(24,0),
  "paid_comments" NUMBER(24,0),
  "paid_likes" NUMBER(24,0), 
  "paid_shares" NUMBER(24,0)
 );

INSERT INTO "ads_insight_fact" 
 (
  "src_id",
  "user_id",
  "account_id", 
  "platform_id",
  "account_name",
  "ads_id",
  "ads_name",
  "created_date",
  "start_date",
  "start_date_ym",
  "start_date_w",
  "modified_date",
  "end_date", 
  "campaign_id" ,
  "campaign_name", 
  "currency_id", 
  "spent_amount", 
  "reach",
  "impressions" , 
  "frequency",
  "cpm", 
  "cpv",
  "link_clicks",
  "ctr",
  "post_comments",
  "post_reactions",
  "post_shares",
  "video_views",
  "view_rate",
  "six_sec_video_view", 
  "full_video_view",
  "est_ad_recall_lift",
  "est_ad_recall_lift_rate",
  "active_view_measurability",
  "landing_page_clicks",
  "paid_comments",
  "paid_likes", 
  "paid_shares"
   )
 SELECT 
 "src_id",
  "user_id",
  "account_id", 
  "platform_id",
  "account_name",
  "ads_id",
  "ads_name",
  "created_date",
  "start_date",
  LEFT(date_trunc ('MONTH',"start_date"),7) AS "start_date_ym",
  CONCAT (YEAR("start_date"), '-',  week ("start_date"), 'w') as "start_date_w",
  "modified_date",
  "end_date", 
  "campaign_id" ,
  "campaign_name", 
  "currency_id", 
  "spent_amount", 
  "reach",
  "impressions" , 
  "frequency",
  "cpm", 
  "cpv",
  "link_clicks",
  "ctr",
  "post_comments",
  "post_reactions",
  "post_shares",
  "video_views",
  "view_rate",
  "six_sec_video_view", 
  "full_video_view",
  "est_ad_recall_lift",
  "est_ad_recall_lift_rate",
  "active_view_measurability",
  "landing_page_clicks",
  "paid_comments",
  "paid_likes", 
  "paid_shares"
  from "sklik";
