{
  processors: {},
  parameters: {
    query: "SET username =  '"+Input("user-name")+"'; -- set user to investigate \nSET s_time = '"+Input("start-time")+"'; -- set start time\nSET e_time = CURRENT_TIMESTAMP;\n\n\n--- This query creats a joined timeline of events from login_history and query_history, taken by a suspected user.\n\n\nWITH query_history AS (\n    SELECT\n    'query' AS log_type,\n        START_TIME,\n        USER_NAME,\n        QUERY_ID,\n        QUERY_TEXT,\n        DATABASE_NAME,\n        QUERY_TYPE,\n        EXECUTION_STATUS,\n        ERROR_CODE,\n        ERROR_MESSAGE,\n        NULL AS EVENT_ID,\n        NULL AS EVENT_TYPE,\n        NULL AS CLIENT_IP,\n        NULL AS FIRST_AUTHENTICATION_FACTOR,\n        NULL AS SECOND_AUTHENTICATION_FACTOR,\n        NULL AS IS_SUCCESS\n    FROM\n        snowflake.account_usage.query_history\n    WHERE\n        USER_NAME = $username\n        AND start_time BETWEEN $s_time AND $e_time\n),\nlogin_history AS (\n    SELECT\n    'login' AS log_type,\n        EVENT_TIMESTAMP AS start_time,\n        USER_NAME,\n        NULL AS QUERY_ID,\n        NULL AS QUERY_TEXT,\n        NULL AS DATABASE_NAME,\n        NULL AS QUERY_TYPE,\n        NULL AS EXECUTION_STATUS,\n        ERROR_CODE,\n        NULL AS ERROR_MESSAGE,\n        EVENT_ID,\n        EVENT_TYPE,\n        CLIENT_IP,\n        FIRST_AUTHENTICATION_FACTOR,\n        SECOND_AUTHENTICATION_FACTOR,\n        IS_SUCCESS\n    FROM\n        snowflake.account_usage.login_history\n    WHERE\n        USER_NAME = $username\n        AND EVENT_TIMESTAMP BETWEEN $s_time AND $e_time\n)\n\nSELECT\n    log_type,\n    start_time,\n    USER_NAME,\n    QUERY_ID,\n    QUERY_TEXT,\n    DATABASE_NAME,\n    QUERY_TYPE,\n    EXECUTION_STATUS,\n    ERROR_CODE,\n    ERROR_MESSAGE,\n    EVENT_ID,\n    EVENT_TYPE,\n    CLIENT_IP,\n    FIRST_AUTHENTICATION_FACTOR,\n    SECOND_AUTHENTICATION_FACTOR,\n    IS_SUCCESS\nFROM\n    query_history\nUNION ALL\nSELECT\n    log_type,\n    start_time,\n    USER_NAME,\n    QUERY_ID,\n    QUERY_TEXT,\n    DATABASE_NAME,\n    QUERY_TYPE,\n    EXECUTION_STATUS,\n    ERROR_CODE,\n    ERROR_MESSAGE,\n    EVENT_ID,\n    EVENT_TYPE,\n    CLIENT_IP,\n    FIRST_AUTHENTICATION_FACTOR,\n    SECOND_AUTHENTICATION_FACTOR,\n    IS_SUCCESS\nFROM\n    login_history\nORDER BY\n    start_time;",
    outputTable: "in.c-keboola-ex-db-snowflake-" + ConfigId("snowflake-security-data-source") + ".user_timeline",
    incremental: false,
    primaryKey: [],
  },
}
