CREATE TABLE `CONTACT_FORM_SUBMISSION` (
  `SUBMITTED_AT` DATETIME,
  `FORM_ID` STRING(2000),
  `CONTACT_ID` STRING(2000),
  `PRE_CUSTOMER_FORM` NUMERIC(38, 0),
  `CREATED_AT_DATE` DATE,
  `CREATED_AT_TIME` TIME
)
INSERT INTO `CONTACT_FORM_SUBMISSION`
SELECT
  DATE_ADD('1970-01-01', INTERVAL (NULLIF(F.`SUBMITTED_AT`, '')) MILLISECOND) AS `SUBMITTED_AT`,
  F.`FORM_ID`,
  F.`CONTACT_ID`,
  IF(
    NULLIF(CON.`TOTAL_REVENUE`, '') > 0
    AND NULLIF(CON.`FIRST_DEAL_CREATED_DATE`, '') > DATE_ADD('1970-01-01', INTERVAL (NULLIF(F.`SUBMITTED_AT`, '')) MILLISECOND),
    1,
    0
  ) AS `PRE_CUSTOMER_FORM`,
  CAST(DATE_ADD('1970-01-01', INTERVAL (NULLIF(F.`SUBMITTED_AT`, '')) MILLISECOND) AS DATE) AS `CREATED_AT_DATE`,
  TIME(DATE_ADD('1970-01-01', INTERVAL (NULLIF(F.`SUBMITTED_AT`, '')) MILLISECOND)) AS `CREATED_AT_TIME`
FROM `HS_CONTACT_FORM_SUBMISSION` AS F
LEFT JOIN `HS_CONTACTS` AS CON
  ON CON.`ID` = F.`CONTACT_ID`;