CREATE TABLE "DEALS"
(
    "ID" VARCHAR(2000), 
    "DEALNAME" VARCHAR(255),
    "HS_FORECAST_AMOUNT" NUMERIC,
    "CREATEDATE" VARCHAR(255),
    "HS_IS_CLOSED" BOOLEAN,
    "HS_DEAL_STAGE_PROBABILITY" NUMERIC, 
    "DAYS_TO_CLOSE" NUMERIC,
    "HS_CREATED_BY_USER_ID" VARCHAR(255), 
    "HS_PROJECTED_AMOUNT" NUMERIC, 
    "HS_IS_CLOSED_WON" BOOLEAN,
    "HS_CLOSED_AMOUNT_IN_HOME_CURRENCY" NUMERIC,
    "DESCRIPTION" VARCHAR(255), 
    "AMOUNT_IN_HOME_CURRENCY" NUMERIC,
    "HS_CLOSED_AMOUNT" NUMERIC,
    "CLOSEDATE" VARCHAR(255),
    "DEALTYPE" VARCHAR(255),
    "AMOUNT" NUMERIC,
    "HS_LASTMODIFIEDDATE" VARCHAR(255),
    "PIPELINE" VARCHAR(255), 
    "DEALSTAGE" VARCHAR(255),
    "PIPELINE_DISPLAY_ORDER" NUMERIC, 
    "HS_DATE_ENTERED_CLOSEDWON" VARCHAR(255),
    "CREATED_AT_DATE" DATE,
    "CREATED_AT_TIME" TIME
);

INSERT INTO "DEALS" 
SELECT D."ID", D."DEALNAME",
D."HS_FORECAST_AMOUNT",D."CREATEDATE",D."HS_IS_CLOSED",D."HS_DEAL_STAGE_PROBABILITY", D."DAYS_TO_CLOSE",
D."HS_CREATED_BY_USER_ID", D."HS_PROJECTED_AMOUNT", D."HS_IS_CLOSED_WON",D."HS_CLOSED_AMOUNT_IN_HOME_CURRENCY",
D."DESCRIPTION", D."AMOUNT_IN_HOME_CURRENCY",D."HS_CLOSED_AMOUNT",D."CLOSEDATE",D."DEALTYPE",D."AMOUNT",D."HS_LASTMODIFIEDDATE",
D."PIPELINE" , PS."LABEL" AS "DEALSTAGE", PS."DISPLAY_ORDER" AS "PIPELINE_DISPLAY_ORDER", 
CASE WHEN D."HS_IS_CLOSED_WON" = 'true' THEN D."CLOSEDATE" ELSE NULL END AS "HS_DATE_ENTERED_CLOSEDWON",
TO_DATE(NULLIF(D."CREATEDATE",'')) AS "CREATED_AT_DATE",
TO_TIME(NULLIF(D."CREATEDATE",'')) AS "CREATED_AT_TIME"
FROM "HS_DEALS" D
LEFT JOIN "HS_DEALS_PIPELINE_STAGES" PS 
ON D."PIPELINE" = PS."PIPELINE_ID" AND D."DEALSTAGE"=PS."ID";