CREATE TABLE `DIM_DATE_TEMP` (
  TABLE_COLUMN STRING(255),
  MIN_DATE STRING(20),
  MAX_DATE STRING(20)
)
/* hubspot_call */
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_CALL__CREATED_AT_DATE' AS `TABLE_COLUMN`,
  MIN(`CREATED_AT_DATE`) AS `MIN_DATE`,
  MAX(`CREATED_AT_DATE`) AS `MAX_DATE`
FROM `CALL`
WHERE
  NOT `CREATED_AT_DATE` IS NULL
/* hubspot_companies */
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_COMPANIES__CREATED_AT_DATE' AS `TABLE_COLUMN`,
  MIN(`CREATED_AT_DATE`) AS `MIN_DATE`,
  MAX(`CREATED_AT_DATE`) AS `MAX_DATE`
FROM `COMPANIES`
WHERE
  NOT `CREATED_AT_DATE` IS NULL
/* hubspot_contacts */
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_CONTACTS__HS_SA_FIRST_ENGAGEMENT_DATE' AS `TABLE_COLUMN`,
  MIN(CAST(NULLIF(`HS_SA_FIRST_ENGAGEMENT_DATE`, '') AS DATE)) AS `MIN_DATE`,
  MAX(CAST(NULLIF(`HS_SA_FIRST_ENGAGEMENT_DATE`, '') AS DATE)) AS `MAX_DATE`
FROM `CONTACTS`
WHERE
  `HS_SA_FIRST_ENGAGEMENT_DATE` <> ''
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_CONTACTS__HS_LAST_SALES_ACTIVITY_DATE' AS `TABLE_COLUMN`,
  MIN(CAST(NULLIF(`HS_LAST_SALES_ACTIVITY_DATE`, '') AS DATE)) AS `MIN_DATE`,
  MAX(CAST(NULLIF(`HS_LAST_SALES_ACTIVITY_DATE`, '') AS DATE)) AS `MAX_DATE`
FROM `CONTACTS`
WHERE
  `HS_LAST_SALES_ACTIVITY_DATE` <> ''
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_CONTACTS__HS_EMAIL_FIRST_CLICK_DATE' AS `TABLE_COLUMN`,
  MIN(CAST(NULLIF(`HS_EMAIL_FIRST_CLICK_DATE`, '') AS DATE)) AS `MIN_DATE`,
  MAX(CAST(NULLIF(`HS_EMAIL_FIRST_CLICK_DATE`, '') AS DATE)) AS `MAX_DATE`
FROM `CONTACTS`
WHERE
  `HS_EMAIL_FIRST_CLICK_DATE` <> ''
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_CONTACTS__FIRST_DEAL_CREATED_DATE' AS `TABLE_COLUMN`,
  MIN(CAST(NULLIF(`FIRST_DEAL_CREATED_DATE`, '') AS DATE)) AS `MIN_DATE`,
  MAX(CAST(NULLIF(`FIRST_DEAL_CREATED_DATE`, '') AS DATE)) AS `MAX_DATE`
FROM `CONTACTS`
WHERE
  `FIRST_DEAL_CREATED_DATE` <> ''
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_CONTACTS__HS_EMAIL_LAST_CLICK_DATE' AS `TABLE_COLUMN`,
  MIN(CAST(NULLIF(`HS_EMAIL_LAST_CLICK_DATE`, '') AS DATE)) AS `MIN_DATE`,
  MAX(CAST(NULLIF(`HS_EMAIL_LAST_CLICK_DATE`, '') AS DATE)) AS `MAX_DATE`
FROM `CONTACTS`
WHERE
  `HS_EMAIL_LAST_CLICK_DATE` <> ''
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_CONTACTS__HS_EMAIL_LAST_SEND_DATE' AS `TABLE_COLUMN`,
  MIN(CAST(NULLIF(`HS_EMAIL_LAST_SEND_DATE`, '') AS DATE)) AS `MIN_DATE`,
  MAX(CAST(NULLIF(`HS_EMAIL_LAST_SEND_DATE`, '') AS DATE)) AS `MAX_DATE`
FROM `CONTACTS`
WHERE
  `HS_EMAIL_LAST_SEND_DATE` <> ''
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_CONTACTS__CLOSEDATE' AS `TABLE_COLUMN`,
  MIN(CAST(NULLIF(`CLOSEDATE`, '') AS DATE)) AS `MIN_DATE`,
  MAX(CAST(NULLIF(`CLOSEDATE`, '') AS DATE)) AS `MAX_DATE`
FROM `CONTACTS`
WHERE
  `CLOSEDATE` <> ''
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_CONTACTS__HS_LATEST_SEQUENCE_ENDED_DATE' AS `TABLE_COLUMN`,
  MIN(CAST(NULLIF(`HS_LATEST_SEQUENCE_ENDED_DATE`, '') AS DATE)) AS `MIN_DATE`,
  MAX(CAST(NULLIF(`HS_LATEST_SEQUENCE_ENDED_DATE`, '') AS DATE)) AS `MAX_DATE`
FROM `CONTACTS`
WHERE
  `HS_LATEST_SEQUENCE_ENDED_DATE` <> ''
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_CONTACTS__FIRST_CONVERSION_DATE' AS `TABLE_COLUMN`,
  MIN(CAST(NULLIF(`FIRST_CONVERSION_DATE`, '') AS DATE)) AS `MIN_DATE`,
  MAX(CAST(NULLIF(`FIRST_CONVERSION_DATE`, '') AS DATE)) AS `MAX_DATE`
FROM `CONTACTS`
WHERE
  `FIRST_CONVERSION_DATE` <> ''
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_CONTACTS__HS_EMAIL_LAST_OPEN_DATE' AS `TABLE_COLUMN`,
  MIN(CAST(NULLIF(`HS_EMAIL_LAST_OPEN_DATE`, '') AS DATE)) AS `MIN_DATE`,
  MAX(CAST(NULLIF(`HS_EMAIL_LAST_OPEN_DATE`, '') AS DATE)) AS `MAX_DATE`
FROM `CONTACTS`
WHERE
  `HS_EMAIL_LAST_OPEN_DATE` <> ''
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_CONTACTS__CREATED_AT_DATE' AS `TABLE_COLUMN`,
  MIN(`CREATED_AT_DATE`) AS `MIN_DATE`,
  MAX(`CREATED_AT_DATE`) AS `MAX_DATE`
FROM `CONTACTS`
WHERE
  NOT `CREATED_AT_DATE` IS NULL
/* hubspot_contact_form_submission */
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_CONTACT_FORM_SUBMISSION__CREATED_AT_DATE' AS `TABLE_COLUMN`,
  MIN(`CREATED_AT_DATE`) AS `MIN_DATE`,
  MAX(`CREATED_AT_DATE`) AS `MAX_DATE`
FROM `CONTACT_FORM_SUBMISSION`
WHERE
  NOT `CREATED_AT_DATE` IS NULL
/* hubspot_deals */
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_DEALS__HS_DATE_ENTERED_CLOSEDWON' AS `TABLE_COLUMN`,
  MIN(CAST(NULLIF(`HS_DATE_ENTERED_CLOSEDWON`, '') AS DATE)) AS `MIN_DATE`,
  MAX(CAST(NULLIF(`HS_DATE_ENTERED_CLOSEDWON`, '') AS DATE)) AS `MAX_DATE`
FROM `DEALS`
WHERE
  `HS_DATE_ENTERED_CLOSEDWON` <> ''
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_DEALS__HS_LASTMODIFIEDDATE' AS `TABLE_COLUMN`,
  MIN(CAST(NULLIF(`HS_LASTMODIFIEDDATE`, '') AS DATE)) AS `MIN_DATE`,
  MAX(CAST(NULLIF(`HS_LASTMODIFIEDDATE`, '') AS DATE)) AS `MAX_DATE`
FROM `DEALS`
WHERE
  `HS_LASTMODIFIEDDATE` <> ''
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_DEALS__CLOSEDATE' AS `TABLE_COLUMN`,
  MIN(CAST(NULLIF(`CLOSEDATE`, '') AS DATE)) AS `MIN_DATE`,
  MAX(CAST(NULLIF(`CLOSEDATE`, '') AS DATE)) AS `MAX_DATE`
FROM `DEALS`
WHERE
  `CLOSEDATE` <> ''
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_DEALS__CREATED_AT_DATE' AS `TABLE_COLUMN`,
  MIN(`CREATED_AT_DATE`) AS `MIN_DATE`,
  MAX(`CREATED_AT_DATE`) AS `MAX_DATE`
FROM `DEALS`
WHERE
  NOT `CREATED_AT_DATE` IS NULL
/* hubspot_email */
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_EMAIL__CREATED_AT_DATE' AS `TABLE_COLUMN`,
  MIN(`CREATED_AT_DATE`) AS `MIN_DATE`,
  MAX(`CREATED_AT_DATE`) AS `MAX_DATE`
FROM `EMAIL`
WHERE
  NOT `CREATED_AT_DATE` IS NULL
/* hubspot_marketing_campaign_sent_date */ /*
INSERT INTO "DIM_DATE_TEMP"
select
   'HUBSPOT_MARKETING_CAMPAIGN_SENT_DATE__DATE_CAMPAIGN_SENT' as "TABLE_COLUMN",
    min(date("DATE_CAMPAIGN_SENT")) as "MIN_DATE",
    max(date("DATE_CAMPAIGN_SENT")) as "MAX_DATE"
from "MARKETING_CAMPAIGN_SENT_DATE"
WHERE "DATE_CAMPAIGN_SENT" IS NOT NULL;
*/ /* hubspot_marketing_email */
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_MARKETING_EMAIL__DATE_CREATED' AS `TABLE_COLUMN`,
  MIN(CAST(`DATE_CREATED` AS DATE)) AS `MIN_DATE`,
  MAX(CAST(`DATE_CREATED` AS DATE)) AS `MAX_DATE`
FROM `MARKETING_EMAIL`
WHERE
  NOT `DATE_CREATED` IS NULL
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_MARKETING_EMAIL__CAMPAIGN_DATE' AS `TABLE_COLUMN`,
  MIN(`CAMPAIGN_DATE`) AS `MIN_DATE`,
  MAX(`CAMPAIGN_DATE`) AS `MAX_DATE`
FROM `MARKETING_EMAIL`
WHERE
  NOT `CAMPAIGN_DATE` IS NULL
/* hubspot_marketing_email_events */
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_MARKETING_EMAIL_EVENTS__CREATED_AT_DATE' AS `TABLE_COLUMN`,
  MIN(`CREATED_AT_DATE`) AS `MIN_DATE`,
  MAX(`CREATED_AT_DATE`) AS `MAX_DATE`
FROM `MARKETING_EMAIL_EVENTS`
WHERE
  NOT `CREATED_AT_DATE` IS NULL
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_MARKETING_EMAIL_EVENTS__SENT_BY_CREATED' AS `TABLE_COLUMN`,
  MIN(CAST(`SENT_BY_CREATED` AS DATE)) AS `MIN_DATE`,
  MAX(CAST(`SENT_BY_CREATED` AS DATE)) AS `MAX_DATE`
FROM `MARKETING_EMAIL_EVENTS`
WHERE
  NOT `SENT_BY_CREATED` IS NULL
/* hubspot_meeting */
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_MEETING__MEETING_DATE' AS `TABLE_COLUMN`,
  MIN(CAST(NULLIF(`MEETING_DATE`, '') AS DATE)) AS `MIN_DATE`,
  MAX(CAST(NULLIF(`MEETING_DATE`, '') AS DATE)) AS `MAX_DATE`
FROM `MEETING`
WHERE
  `MEETING_DATE` <> ''
INSERT INTO `DIM_DATE_TEMP`
SELECT
  'HUBSPOT_MEETING__CREATED_AT' AS `TABLE_COLUMN`,
  MIN(CAST(NULLIF(`CREATED_AT`, '') AS DATE)) AS `MIN_DATE`,
  MAX(CAST(NULLIF(`CREATED_AT`, '') AS DATE)) AS `MAX_DATE`
FROM `MEETING`
WHERE
  `CREATED_AT` <> ''
CREATE TABLE `DIM_DATE` (
  DATE_ORDER INT64,
  DATE DATE
)
INSERT INTO `DIM_DATE`
SELECT
  -1 + ROW_NUMBER() OVER (ORDER BY 0 NULLS LAST) AS i,
  start_date + i AS generated_date
FROM (
  SELECT
    CAST(MIN(`MIN_DATE`) AS DATE) AS start_date,
    CAST(MAX(`MAX_DATE`) AS DATE) AS end_date
  FROM `DIM_DATE_TEMP`
  WHERE
    `MIN_DATE` <> '' AND `MAX_DATE` <> ''
), table(generator(rowcount => 10000)) AS x
QUALIFY
  i < 1 + end_date - start_date;