CREATE TABLE `OWNER` (
  `ID` STRING(2000),
  `EMAIL` STRING(255),
  `FIRST_NAME` STRING(255),
  `LAST_NAME` STRING(255),
  `USER_ID` STRING(255),
  `ARCHIVED` BOOL
)
INSERT INTO `OWNER`
SELECT
  `ID`,
  `EMAIL`,
  `FIRST_NAME`,
  `LAST_NAME`,
  `USER_ID`,
  `ARCHIVED`
FROM `HS_OWNERS`;