CREATE TABLE "FORMS"
(
    "GUID" VARCHAR(2000),
    "NAME" VARCHAR(2000)
);

INSERT INTO "FORMS"
SELECT "GUID","NAME" AS "FORM_NAME", "ACTION", "SUBMIT_TEXT", "LEAD_NURTURING_CAMPAIGN_ID" 
FROM "HS_FORMS";
