CREATE TABLE `EMAIL` (
  `HTML` STRING(2000),
  `FROM_EMAIL` STRING(255),
  `SENDER_EMAIL` STRING(255),
  `SUBJECT` STRING(255),
  `TEXT` STRING(2000),
  `STATUS` STRING(255),
  `FROM_FIRST_NAME` STRING(255),
  `FROM_LAST_NAME` STRING(255),
  `CREATED_AT` STRING(255),
  `CREATED_BY` STRING(255),
  `ID` STRING(2000),
  `CONTACT_ID` STRING(2000),
  `PRE_CUSTOMER_EMAIL` STRING(255),
  `CREATED_AT_DATE` DATE,
  `CREATED_AT_TIME` TIME
)
INSERT INTO `EMAIL`
SELECT
  EM.`HTML`,
  EM.`FROM_EMAIL`,
  EM.`SENDER_EMAIL`,
  EM.`SUBJECT`,
  EM.`TEXT`,
  EM.`STATUS`,
  EM.`FROM_FIRST_NAME`,
  EM.`FROM_LAST_NAME`,
  DATE_ADD('1970-01-01', INTERVAL E.`CREATED_AT` MILLISECOND) AS `CREATED_AT`,
  E.`CREATED_BY`,
  E.`ID`,
  CE.`CONTACT_ID`,
  IF(
    CON.`TOTAL_REVENUE` > 0
    AND CON.`FIRST_DEAL_CREATED_DATE` > DATE_ADD('1970-01-01', INTERVAL E.`CREATED_AT` MILLISECOND),
    1,
    0
  ) AS `PRE_CUSTOMER_EMAIL`,
  CAST(DATE_ADD('1970-01-01', INTERVAL E.`CREATED_AT` MILLISECOND) AS DATE) AS `CREATED_AT_DATE`,
  TIME(DATE_ADD('1970-01-01', INTERVAL E.`CREATED_AT` MILLISECOND)) AS `CREATED_AT_TIME`
FROM `HS_ENGAGEMENT_EMAIL` AS EM
LEFT JOIN `HS_ENGAGEMENTS` AS E
  ON EM.`ENGAGEMENT_ID` = E.`ID`
LEFT JOIN `HS_CONTACT_ENGAGEMENT_ASSOCIATION` AS CE
  ON CE.`ENGAGEMENT_ID` = E.`ID`
LEFT JOIN `HS_CONTACTS` AS CON
  ON CON.`ID` = CE.`CONTACT_ID`;