CREATE OR REPLACE TABLE "tiktok"(
  "src_id" varchar (100),
  "user_id" varchar (100) ,
  "account_id" varchar (100), 
  "platform_id" varchar(100),
  "account_name" varchar (100),
  "ads_id" integer ,
  "ads_name" varchar (100) ,
  "created_date" date,
  "start_date" date,
  "modified_date" date,
  "end_date" date, 
  "campaign_id" integer,
  "campaign_name" varchar (100), 
  "currency_id" varchar (10), 
  "spent_amount" NUMBER(24,3), 
  "reach" NUMBER(24,0),
  "impressions" NUMBER(24,0), 
  "frequency" NUMBER(24,3),
  "cpm" NUMBER(24,3), 
  "cpv" NUMBER(24,3),
  "link_clicks" NUMBER(24,0),
  "ctr" NUMBER(24,3),
  "post_comments" NUMBER(24,0),
  "post_reactions" NUMBER(24,0),
  "post_shares" NUMBER(24,0),
  "video_views" NUMBER(24,0),
  "view_rate"  NUMBER(24,0),
  "six_sec_video_view" NUMBER(24,0), 
  "full_video_view" NUMBER(24,0),
  "est_ad_recall_lift" NUMBER(24,0),
  "est_ad_recall_lift_rate" NUMBER(24,3),
  "active_view_measurability" NUMBER(24,3),
  "landing_page_clicks" NUMBER(24,0),
  "paid_comments" NUMBER(24,0),
  "paid_likes" NUMBER(24,0), 
  "paid_shares" NUMBER(24,0)
 )
 ;

INSERT INTO "tiktok" 
(
"src_id",
   "user_id",
  "account_id",
  "platform_id", 
  "account_name",
  "ads_id",
  "ads_name",
  "created_date",
  "start_date" , 
  "modified_date" , 
  "end_date" , 
  "campaign_id" , 
  "campaign_name" , 
  "currency_id" , 
  "spent_amount" ,
  "reach",
  "impressions", 
  "frequency",
  "cpm", 
  "link_clicks",
  "ctr",
  "cpv",
  "post_comments",
  "post_reactions",
  "post_shares",
  "video_views",
  "view_rate",
  "six_sec_video_view",
  "full_video_view",
  "est_ad_recall_lift",
  "est_ad_recall_lift_rate",
  "active_view_measurability",
  "landing_page_clicks",
  "paid_comments",
  "paid_likes", 
  "paid_shares" 
)
SELECT 
    concat ('TIKTOK.', A."ad_id",'.', date(A."stat_time_day")),
    NULL,
    --C."ex_advertiser_id",
    substr(C."campaign_name",1, charindex('-',C."campaign_name")-1),
    'TIKTOK',
    substr(C."campaign_name",1, charindex('-',C."campaign_name")-1),
    A."ad_id",
    A."ad_name",
    NULL,
    A."stat_time_day",
    NULL,
    NULL,
    C."campaign_id",
    C."campaign_name",
    A."currency",
    A."spend",
    A."reach",
    A."impressions",
    A."frequency",
    A."cpm",
    NULL, --??
    A."ctr",
    NULL,
    NULL, --?
    NULL, --?
    NULL, --?
    A."video_play_actions",
    NULL,
    A."video_watched_6s",
    A."video_views_p100",
    NULL,
    NULL,
    NULL,
    NULL,
    A."comments",
    A."likes",
    A."shares"
FROM "tiktok_ad" A
JOIN "tiktok_adgroup" AG
    ON A."adgroup_id" = AG."adgroup_id"
JOIN "tiktok_campaign" C
    ON C."campaign_id" = AG."campaign_id"  
;
