CREATE TABLE "COMPANY_CONTACT"
(
    "CONTACT_ID" VARCHAR(2000),
    "COMPANY_ID" VARCHAR(2000),
    "TYPE" VARCHAR(255)
);

CREATE OR REPLACE TABLE "COMPANY_CONTACT" AS
SELECT "CONTACT_ID", "COMPANY_ID", "TYPE" FROM "HS_CONTACT_COMPANY_ASSOCIATION";
