CREATE TABLE `bdmCustomerEnrich` AS
WITH data_all AS (
  SELECT
    `ORDER_CUSTOMER_EMAIL`,
    MAX(`ORDER_DATE`) AS `MAX_ORDER_DATE`,
    COUNT(`ORDER_ID`) AS `N_ORDERS`,
    AVG(`ORDER_TOTAL_PRICE_WITH_TAXES`) AS `AVG_ORDER_TOTAL_PRICE_WITH_VAT`,
    AVG(`ORDER_TOTAL_PRICE_WITHOUT_TAXES`) AS `AVG_ORDER_TOTAL_PRICE_WITHOUT_VAT`
  FROM `bdmOrders` AS o
  WHERE
    `ORDER_STATUS` = 'success'
  GROUP BY
    `ORDER_CUSTOMER_EMAIL`
)
SELECT
  d.`ORDER_CUSTOMER_EMAIL`,
  CAST(`MAX_ORDER_DATE` AS DATE) AS `MAX_ORDER_DATE`,
  `N_ORDERS`,
  `AVG_ORDER_TOTAL_PRICE_WITH_VAT`,
  `AVG_ORDER_TOTAL_PRICE_WITHOUT_VAT`,
  o.`CUSTOMER_REGULARITY_TYPE`
FROM data_all AS d
LEFT JOIN `bdmOrders` AS o
  ON d.`ORDER_CUSTOMER_EMAIL` = o.`ORDER_CUSTOMER_EMAIL`
  AND d.`MAX_ORDER_DATE` = o.`ORDER_DATE`
WHERE
  o.`ORDER_STATUS` = 'success'
UNION ALL
SELECT
  'test1' AS `ORDER_CUSTOMER_EMAIL`,
  '2022-02-07' AS `MAX_ORDER_DATE`,
  '1' AS `N_ORDERS`,
  '208' AS `AVG_ORDER_TOTAL_PRICE_WITH_VAT`,
  '171.9' AS `AVG_ORDER_TOTAL_PRICE_WITHOUT_VAT`,
  'New Customer' AS `CUSTOMER_REGULARITY_TYPE`
WHERE
  (
    SELECT
      COUNT(*)
    FROM data_all
  ) = 0