CREATE TABLE `COMPANY_CONTACT` (
  `CONTACT_ID` STRING(2000),
  `COMPANY_ID` STRING(2000),
  `TYPE` STRING(255)
)
CREATE OR REPLACE TABLE `COMPANY_CONTACT` AS
SELECT
  `CONTACT_ID`,
  `COMPANY_ID`,
  `TYPE`
FROM `HS_CONTACT_COMPANY_ASSOCIATION`;