CREATE TABLE "bdmCustomerEnrich" as
with data as (
select
"ORDER_CUSTOMER_EMAIL",
max("ORDER_DATE") "MAX_ORDER_DATE",
count("ORDER_ID") "N_ORDERS",
avg("ORDER_TOTAL_PRICE_WITH_WAT") "AVG_ORDER_TOTAL_PRICE_WITH_VAT",
avg("ORDER_TOTAL_PRICE_WITHOUT_WAT") "AVG_ORDER_TOTAL_PRICE_WITHOUT_VAT"
  
from "bdmOrders" o
  where "ORDER_STATUS" = 'success'
group by "ORDER_CUSTOMER_EMAIL"
)
select 
d."ORDER_CUSTOMER_EMAIL",
date("MAX_ORDER_DATE") "MAX_ORDER_DATE",
"N_ORDERS",
"AVG_ORDER_TOTAL_PRICE_WITH_VAT",
"AVG_ORDER_TOTAL_PRICE_WITHOUT_VAT",
o."CUSTOMER_REGULARITY_TYPE" 
from data d
left join "bdmOrders" o ON d."ORDER_CUSTOMER_EMAIL" = o."ORDER_CUSTOMER_EMAIL"
AND d."MAX_ORDER_DATE" = o."ORDER_DATE"
 where o."ORDER_STATUS" = 'success';
