CREATE TABLE "MARKETING_EMAIL_EVENTS"
(
    "APP_ID" VARCHAR(2000),
    "APP_NAME" VARCHAR(255),
    "CREATED" TIMESTAMP,
    "EMAIL_CAMPAIGN_ID" VARCHAR(2000),
    "ID" VARCHAR(2000),
    "PORTAL_ID" VARCHAR(2000),
    "RECIPIENT" VARCHAR(255),
    "TYPE" VARCHAR(255),
    "SENT_BY_CREATED" TIMESTAMP,
    "SENT_BY_ID" VARCHAR(2000),
    "BROWSER_NAME" VARCHAR(255),
    "LOCATION_CITY" VARCHAR(255),
    "LOCATION_COUNTRY" VARCHAR(255),
    "LOCATION_STATE" VARCHAR(255),
    "USER_AGENT" VARCHAR(255),
    "DURATION" NUMERIC,
    "SOURCE" VARCHAR(255),
    "PORTAL_SUBSCRIPTION_STATUS" VARCHAR(255),
    "ATTEMPT" VARCHAR(255),
    "RESPONSE" VARCHAR(255),
    "URL" VARCHAR(2000),
    "SUBJECT" VARCHAR(255),
    "FROM_EMAIL" VARCHAR(255),
    "DROP_MESSAGE" VARCHAR(255),
    "CAUSED_BY_ID" VARCHAR(255),
    "PRE_CUSTOMER_MARKETING_EMAIL" NUMERIC,
    "CREATED_AT_DATE" DATE,
    "CREATED_AT_TIME" TIME
);

INSERT INTO "MARKETING_EMAIL_EVENTS"
SELECT E."APP_ID",E."APP_NAME", 
CASE WHEN E."CREATED" <> '' THEN DATEADD('MS',E."CREATED",'1970-01-01') ELSE NULL END AS "CREATED", 
E."EMAIL_CAMPAIGN_ID", E."ID", E."PORTAL_ID", E."RECIPIENT", E."TYPE", 
CASE WHEN E."SENT_BY_CREATED" <> '' THEN DATEADD('MS',E."SENT_BY_CREATED",'1970-01-01') ELSE NULL END AS "SENT_BY_CREATED", 
E."SENT_BY_ID", E."BROWSER_NAME", E."LOCATION_CITY",
E."LOCATION_COUNTRY", E."LOCATION_STATE", E."USER_AGENT", E."DURATION", E."SOURCE", E."PORTAL_SUBSCRIPTION_STATUS",
E."ATTEMPT", E."RESPONSE",E."URL", E."SUBJECT", E."FROM" AS "FROM_EMAIL", E."DROP_MESSAGE", E."CAUSED_BY_ID",
IFF(NULLIF(CON."TOTAL_REVENUE",'') > 0 AND E.TYPE='SENT' AND NULLIF(CON."FIRST_DEAL_CREATED_DATE",'') > (CASE WHEN E."CREATED" <> '' THEN DATEADD('MS',E."CREATED",'1970-01-01') ELSE NULL END),1,0)  AS "PRE_CUSTOMER_MARKETING_EMAIL",
CASE WHEN E."CREATED" <> '' THEN TO_DATE(DATEADD('MS',E."CREATED",'1970-01-01')) ELSE NULL END AS "CREATED_AT_DATE",
CASE WHEN E."CREATED" <> '' THEN TO_TIME(DATEADD('MS',E."CREATED",'1970-01-01')) ELSE NULL END AS "CREATED_AT_TIME"
FROM "HS_EMAIL_EVENTS" E
LEFT JOIN "HS_CONTACTS" CON 
ON E."RECIPIENT"=CON."EMAIL";
