name: 'Push CI'

on:
  push:
    branches:
      - "*"
jobs:
  json-validation:
    name: "JSON validation"
    secrets: inherit
    uses: ./.github/workflows/json-validation.yml

  local-test:
    name: "Run local tests"
    secrets: inherit
    uses: ./.github/workflows/local-tests.yml
